# .github/workflows/release.yml

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            target: "x86_64-unknown-linux-gnu"
          - platform: "windows-2025"
            target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      # 安装 Rust
      - name: install Rust
        if: matrix.target == 'aarch64-unknown-linux-musl'
        uses: dtolnay/rust-toolchain@nightly
        id: rust_toolchain
        with:
          target: ${{ matrix.target }}

      # 编译项目
      - name: Build release
        run: |
          cargo build --release

      # 准备部署工件
      - name: Prepare Artifact
        run: |
          mkdir -p deploy
          cp target/${{ matrix.target }}/release/dirmap deploy/dirmap-${{ matrix.target }}

      # 上传编译产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dirmap-${{ matrix.target }}
          path: deploy/dirmap-${{ matrix.target }}
